apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-17T12:43:23Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "9302"
  uid: 2b37e740-1678-40c3-8781-b89b7942e769
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.104.135.198
  clusterIPs:
  - 10.104.135.198
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31842
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
